### ISSUE TITLE
Need to do following, please confirm.

### ISSUE THREAD

**Issue by naman223** [amitdix/problems#3]
As per email it's mention: GitHub Test Link: https://github.com/amitdix/problems#rest-apis (Cover only Rest API, please ignore remaining)

- **So no need to anything related to kafka.** Only work on REST API. Please confirm this?

- Create REST API as below
1. POST endpoint to create products (one product at a time)
2. GET endpoint to fetch product details
3. PUT end point to update product details
4. POST endpoint to create products price (one product at a time)
5. GET endpoint to fetch product price (for a product)

**Comment by devamitdixit** [comment]
yes @naman223

**Comment by naman223** [comment]
Completed and sent github link on email.
